tradeproject/tradeapp/urls.py
from . import views
from django.urls import path

app_name= 'trade'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('dashboard', views.UserDashboard.as_view(), name='dashboard'),
    path('accounts', views.UserAccount.as_view(), name='accounts'),
    path('settings', views.UserSettings.as_view(), name='settings'),
    path('transactions', views.UserTransactions.as_view(), name='transactions'),


]

tradeproject/tradeproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tradeapp.urls')),
    path('', include('user.urls')),
]

tradeproject/user/__pycache__/tradeapp/urls.py
from . import views
from django.urls import path

app_name= 'trade'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home')

]

tradeproject/user/urls.py
from . import views
from django.urls import path

urlpatterns=[

    path('signin/', views.Signin.as_view(), name='sign_in'),
    path('signup/', views.Signup.as_view(), name='sign_up'),
    path('lost_session', views.Logout.as_view(), name='logout'),
    path('account_verification/', views.Account_verification.as_view(), name='account_verification'),
    path('forgot_password/', views.LostPassword.as_view(), name='forgot_password'),

]

tradeproject/tradeapp/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone



# Create your models here.

class Capital(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,blank=True)
    user_capital = models.DecimalField(decimal_places=1, default=0, max_digits=500000)

    def __str__(self):
        return self.user.username


class Unpaid_user(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,blank=True)
    capital = models.DecimalField(decimal_places=1, default=0, max_digits=500000)
    amount_to_pay= models.DecimalField(decimal_places=1, default=0, max_digits=500000)
    amount_merged= models.DecimalField(decimal_places=1, default=0, max_digits=500000)
    merged_to_pay= models.BooleanField(default=False)
    merged_completed= models.BooleanField(default=False)
    account_paying_to= models.CharField(max_length=200, blank=True, null=True)
    payment_completed= models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Paid_user(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user',null=True, blank=True)
    user_account_number= models.CharField(max_length=30, blank=True, null=True)
    date_paid= models.DateTimeField(default=timezone.now)

    interest= models.DecimalField(decimal_places=1, default=0, max_digits=500000)
    amount_to_receive= models.DecimalField(decimal_places=1, default=0, max_digits=500000, blank=True, null=True)
    amount_merged= models.DecimalField(decimal_places=1, default=0, max_digits=500000)
    merged_to_receive = models.BooleanField(default=False)
    merged_completed = models.BooleanField(default=False)


    receiving_from= models.CharField(max_length=200, blank=True, null=True)
    payment_completed= models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

tradeproject/user/__pycache__/tradeapp/models.py
from django.db import models


# Create your models here.

tradeproject/tradeapp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.views.generic import (View, TemplateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Capital, Unpaid_user, Paid_user

# Create your views here.

class HomeView(TemplateView):

    template_name = 'trade/home.html'


class UserDashboard(LoginRequiredMixin, View):
    login_url = 'sign_in'


def get(self, request):
    # get paid and unpaid users

    paid = Paid_user.objects.filter(merged_to_receive=False)
    unpaid = Unpaid_user.objects.filter(merged_to_pay=False)

    print(unpaid)
    print(paid)

    # ussing while loop for mergig
    while paid.count() != 0 and unpaid.count() != 0:

        receiver = paid[0]
        payer = unpaid[0]

        print(receiver)
        print(payer)

        valu = payer.amount_to_pay - receiver.amount_to_merge

        print(valu)

        if valu < 0:

            print('yes am less than 0')

            receiver.amount_merged += payer.amount_to_pay
            receiver.amount_to_merge = (-+valu)
            receiver.save()

            #########create receivers table and dispatch mail################

            user = payer.user
            receivers_id = receiver.id
            amount = payer.amount_to_pay

            payer.amount_merged += payer.amount_to_pay
            payer.amount_to_pay = 0.0
            payer.merged_to_pay = True
            payer.save()

            print(paid)
            print(unpaid)

            #########create payers transaction table and dispatch mail ################

            payer_transaction_table = PTransaction.objects.create(user=user, receivers_id=receivers_id, amount=amount)

            break
        else:
            print('no valu is greater than 0')

            payer.amount_merged += receiver.amount_to_merge
            payer.amount_to_pay = valu
            payer.save()

            if valu == 0.0:
                payer.merged_to_pay = True
                payer.save()

            receiver.amount_merged += receiver.amount_to_receive
            receiver.amount_to_merge = 0.0
            receiver.merged_to_receive = True
            receiver.save()

            print(paid)
            print(unpaid)
    return render(request, 'dashboard/dashboard.html')


class UserTransactions(View):
    def get(self, request):

        return render(request, 'dashboard/transactions.html')


class UserAccount(View):
    def get(self, request):
        return render(request, 'dashboard/accounts.html')


class UserSettings(View):

    def get(self, request):
        return render(request, 'dashboard/settings.html')

tradeproject/user/__pycache__/tradeapp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.views.generic import (View, TemplateView)
# Create your views here.

class HomeView(TemplateView):

    template_name = 'trade/home.html'

tradeproject/tradeapp/templates/dashboard/dashbase.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<!-- Mirrored from quixlab.com/demo/tradix/dark/dashboard.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 13 Oct 2020 10:55:13 GMT -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tradix </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}"/>
    <!-- Custom Stylesheet -->
    <link rel="stylesheet" href="{% static 'vendor/nice-select/css/nice-select.css' %}"/>
    <link rel="stylesheet" href="{% static 'vendor/waves/waves.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'vendor/toastr/toastr.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>

<body>

    <div id="preloader">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
    </div>

    <div id="main-wrapper">

        <div class="header dashboard">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xl-12">
                        <nav class="navbar navbar-expand-lg navbar-light px-0 justify-content-between">
                            <a class="navbar-brand" href="index.html"><img src="images/logo.png" alt=""></a>

                            <div class="dashboard_log my-2">
                                <div class="d-flex align-items-center">
                                    <div class="account_money">
                                        <ul>
                                            <li class="crypto">
                                                <span>0.0025</span>
                                                <i class="cc BTC"></i>
                                            </li>
                                            <li class="usd">
                                                <span>19.93 USD</span>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="profile_log dropdown">
                                        <div class="user" data-toggle="dropdown">
                                            <span class="thumb"><i class="la la-user"></i></span>
                                            <span class="name">Maria Pascle</span>
                                            <span class="arrow"><i class="la la-angle-down"></i></span>
                                        </div>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a href="#" class="dropdown-item">
                                                <i class="la la-user"></i> Account
                                            </a>
                                            <a href="#" class="dropdown-item">
                                                <i class="la la-book"></i> History
                                            </a>
                                            <a href="#" class="dropdown-item">
                                                <i class="la la-cog"></i> Setting
                                            </a>
                                            <a href="#" class="dropdown-item">
                                                <i class="la la-lock"></i> Lock
                                            </a>
                                            <a href="{% url 'logout' %}" class="dropdown-item logout">
                                                <i class="la la-sign-out"></i> Logout
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        <div class="sidebar">
            <div class="menu">
                <ul>
                    <li>
                        <a href="{% url 'trade:dashboard' %}" data-toggle="tooltip" data-placement="right" title="Home">
                            <span><i class="la la-igloo"></i></span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'trade:transactions' %}" data-toggle="tooltip" data-placement="right" title="Transactions">
                            <span><i class="la la-exchange"></i></span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'trade:accounts' %}" data-toggle="tooltip" data-placement="right" title="Account">
                            <span><i class="la la-user"></i></span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'trade:settings' %}" data-toggle="tooltip" data-placement="right" title="Setting">
                            <span><i class="la la-tools"></i></span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>


  {% block body %} {% endblock %}



          <div class="footer dashboard">
              <div class="container-fluid">
                  <div class="row">
                      <div class="col-xl-6">
                          <div class="copyright">
                              <p>© Copyright 2020 <a href="#">Tradix</a> I All Rights Reserved</p>
                          </div>
                      </div>
                      <div class="col-xl-6">
                          <div class="footer-social">
                              <ul>
                                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                  <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                  <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
          </div>

          <!--removeIf(production)-->
          <!--**********************************
              Right sidebar start
          ***********************************-->
          <div class="sidebar-right">
              <a class="sidebar-right-trigger" href="javascript:void(0)">
                  <span><i class="fa fa-cog fa-spin"></i></span>
              </a>
              <div class="sidebar-right-inner">
                  <div class="admin-settings">
                      <div class="opt-background">
                          <p>Font Family</p>
                          <select class="form-control" name="theme_font" id="theme_font">
                              <option value="nunito">Nunito</option>
                              <option value="poppins">Poppins</option>

                              <option value="opensans">Open Sans</option>

                          </select>
                      </div>
                      <div>
                          <p>Primary Color</p>
                          <div class="opt-nav-header-color">
                              <span>
                                  <input type="radio" name="navigation_header" value="color_1"
                                      class="filled-in chk-col-primary" id="nav_header_color_1" />
                                  <label for="nav_header_color_1"></label>
                              </span>
                              <span>
                                  <input type="radio" name="navigation_header" value="color_2"
                                      class="filled-in chk-col-primary" id="nav_header_color_2" />
                                  <label for="nav_header_color_2"></label>
                              </span>
                              <span>
                                  <input type="radio" name="navigation_header" value="color_3"
                                      class="filled-in chk-col-primary" id="nav_header_color_3" />
                                  <label for="nav_header_color_3"></label>
                              </span>
                              <span>
                                  <input type="radio" name="navigation_header" value="color_4"
                                      class="filled-in chk-col-primary" id="nav_header_color_4" />
                                  <label for="nav_header_color_4"></label>
                              </span>
                              <span>
                                  <input type="radio" name="navigation_header" value="color_5"
                                      class="filled-in chk-col-primary" id="nav_header_color_5" />
                                  <label for="nav_header_color_5"></label>
                              </span>
                          </div>
                      </div>
                      <div class="opt-header-color">
                          <p>Background Color</p>
                          <div>
                              <span>
                                  <input type="radio" name="header_bg" value="color_1" class="filled-in chk-col-primary"
                                      id="header_color_1">
                                  <label for="header_color_1"></label>
                              </span>
                              <span>
                                  <input type="radio" name="header_bg" value="color_2" class="filled-in chk-col-primary"
                                      id="header_color_2">
                                  <label for="header_color_2"></label>
                              </span>
                              <span>
                                  <input type="radio" name="header_bg" value="color_3" class="filled-in chk-col-primary"
                                      id="header_color_3">
                                  <label for="header_color_3"></label>
                              </span>
                              <span>
                                  <input type="radio" name="header_bg" value="color_4" class="filled-in chk-col-primary"
                                      id="header_color_4">
                                  <label for="header_color_4"></label>
                              </span>
                              <span>
                                  <input type="radio" name="header_bg" value="color_5" class="filled-in chk-col-primary"
                                      id="header_color_5">
                                  <label for="header_color_5"></label>
                              </span>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <!--**********************************
              Right sidebar end
          ***********************************-->
          <!--endRemoveIf(production)-->

      </div>



      <script src="{% static 'js/global.js' %}"></script>
      <script src="{% static 'vendor/toastr/toastr.min.js' %}"></script>
      <script src="{% static 'vendor/toastr/toastr-init.js' %}"></script>
      <script src="{% static 'vendor/circle-progress/circle-progress.min.js' %}"></script>
      <script src="{% static 'vendor/circle-progress/circle-progress-init.js' %}"></script>

      <!--  flot-chart js -->
      <script src="{% static 'vendor/apexchart/apexcharts.min.js' %}"></script>
      <script src="{% static 'vendor/apexchart/apexchart-init.js' %}"></script>


      <!-- <script src="./js/dashboard.js"></script> -->
      <script src="{% static 'js/dashboard.js' %}"></script>
      <script src="{% static 'js/scripts.js' %}"></script>

      <script src="{% static 'js/settings.js' %}"></script>
      <script src="{% static 'js/quixnav-init.js' %}"></script>
      <script src="{% static 'js/styleSwitcher.js' %}"></script>
  </body>


  <!-- Mirrored from quixlab.com/demo/tradix/dark/dashboard.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 13 Oct 2020 10:55:25 GMT -->
  </html>